apiVersion: v1
kind: Pod
metadata:
  name: python-microservice
  labels:
    app: python-microservice
spec:
  containers:
  - name: python-microservice
    image: adybfjcns/python-microservice:${DOCKER_TAG}
---
apiVersion: v1
kind: Service
metadata:
  name: python-microservice
  labels:
    app: python-microservice
spec:
  type: NodePort
  selector:
    app: python-microservice
  ports:
  - name: "flask"
    port: 5000
    targetPort: 5000
    nodePort: 30500
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-microservice
  annotations:
    # Path routing only seems to work when this is applied
    ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
        - path: /python
          backend:
            serviceName: python-microservice
            servicePort: 5000
  - host: localhost
    http:
      paths:
        - path: /python
          backend:
            serviceName: python-microservice
            servicePort: 5000